# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home_inspection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingCode', models.CharField(max_length=20)),
                ('buildingName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(max_length=255)),
                ('faultDescription', models.CharField(max_length=1000)),
                ('faultPhoto', models.FileField(upload_to='uploads', validators=[home_inspection.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('propertySize', models.DecimalField(decimal_places=4, max_digits=5)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('buildingType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_inspection.BuildingType')),
                ('inspectorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_inspection.Inspector')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_inspection.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCode', models.CharField(max_length=20)),
                ('typeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=255)),
                ('propertyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_inspection.Property')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomCode', models.CharField(max_length=20)),
                ('roomTypeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='roomTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_inspection.RoomType'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_inspection.PropertyType'),
        ),
        migrations.AddField(
            model_name='component',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_inspection.Room'),
        ),
    ]
