# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
