# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0003_auto_20161217_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ownerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_inspection.Owner'),
        ),
    ]
