# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import home_inspection.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0006_remove_component_faultphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='faultPhoto',
            field=models.FileField(null=True, upload_to='uploads', validators=[home_inspection.models.validate_file_extension]),
        ),
    ]
