# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0009_auto_20170117_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspector',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='property',
            name='buildingTypeId',
        ),
        migrations.AddField(
            model_name='property',
            name='client',
            field=models.CharField(default='not_provided', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='projectNum',
            field=models.CharField(default=' ', max_length=45),
            preserve_default=False,
        ),
    ]
