# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0010_auto_20170117_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='inspectorId',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ownerId',
        ),
        migrations.AlterField(
            model_name='inspector',
            name='description',
            field=models.CharField(max_length=450),
        ),
    ]
