# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0013_auto_20170129_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='password',
        ),
    ]
