# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0016_auto_20170129_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspector',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='memberStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='undefined', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='undefined', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='undefined', max_length=75),
        ),
    ]
