# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0017_auto_20170218_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75)),
                ('company', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=450, null=True)),
                ('password', models.CharField(max_length=25)),
                ('subscriptionStatus', models.BooleanField(default=False)),
                ('memberStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MC', 'Mastercard'), ('VS', 'Visa'), ('PP', 'Paypal'), ('DT', 'Debit')], max_length=2),
        ),
    ]
