# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0002_property_isdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='buildingType',
            new_name='buildingTypeId',
        ),
        migrations.AlterField(
            model_name='property',
            name='propertySize',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
