# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0005_auto_20161217_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='faultPhoto',
        ),
    ]
