# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_inspection', '0008_remove_component_faultphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75)),
            ],
        ),
        migrations.RenameField(
            model_name='inspector',
            old_name='lastname',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='lastname',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='inspector',
            name='firstname',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='owner',
            name='firstname',
            field=models.CharField(max_length=75),
        ),
    ]
